"""initial_schema

Revision ID: 236606bbc6f5
Revises: 
Create Date: 2026-07-03 08:50:52.269027

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '236606bbc6f5'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('operator', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('algorithm', sa.String(), nullable=False),
    sa.Column('algorithm_params', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_runs', schema=None) as batch_op:
        batch_op.create_index('idx_calibration_runs_in_progress', ['robot_id', 'kind'], unique=False, sqlite_where=sa.text("status = 'in_progress'"), postgresql_where=sa.text("status = 'in_progress'"))

    op.create_table('scan_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'session_id')
    )
    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.create_index('idx_scan_sessions_robot', ['robot_id', 'created_at'], unique=False)

    op.create_table('calibration_captures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('pose_index', sa.Integer(), nullable=False),
    sa.Column('motor_positions', sa.Text(), nullable=True),
    sa.Column('board_in_cam', sa.Text(), nullable=True),
    sa.Column('corners_2d', sa.Text(), nullable=True),
    sa.Column('corner_ids', sa.Text(), nullable=True),
    sa.Column('reproj_rms_px', sa.Float(), nullable=True),
    sa.Column('tilt_deg', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['calibration_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_captures', schema=None) as batch_op:
        batch_op.create_index('idx_calibration_captures_run', ['run_id', 'pose_index'], unique=False)

    op.create_table('calibration_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sigma_rot', sa.Float(), nullable=True),
    sa.Column('sigma_t', sa.Float(), nullable=True),
    sa.Column('effective_sigma_rot', sa.Float(), nullable=True),
    sa.Column('effective_sigma_t', sa.Float(), nullable=True),
    sa.Column('result_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['calibration_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calibration_results', schema=None) as batch_op:
        batch_op.create_index('idx_calibration_results_active', ['robot_id', 'kind'], unique=True, sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = TRUE'))
        batch_op.create_index('idx_calibration_results_lookup', ['robot_id', 'kind', 'created_at'], unique=False)

    op.create_table('reconstructions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_row_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blob_key', sa.String(), nullable=False),
    sa.Column('voxel_size', sa.Float(), nullable=False),
    sa.Column('sdf_trunc', sa.Float(), nullable=False),
    sa.Column('depth_trunc', sa.Float(), nullable=False),
    sa.Column('icp_max_dist', sa.Float(), nullable=False),
    sa.Column('n_scans', sa.Integer(), nullable=False),
    sa.Column('n_edges', sa.Integer(), nullable=False),
    sa.Column('vertex_count', sa.Integer(), nullable=False),
    sa.Column('triangle_count', sa.Integer(), nullable=False),
    sa.Column('elapsed', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['session_row_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconstructions', schema=None) as batch_op:
        batch_op.create_index('idx_reconstructions_session', ['session_row_id', 'created_at'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_row_id', sa.Integer(), nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('blob_key', sa.String(), nullable=False),
    sa.Column('num_frames', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('fx', sa.Float(), nullable=False),
    sa.Column('fy', sa.Float(), nullable=False),
    sa.Column('cx', sa.Float(), nullable=False),
    sa.Column('cy', sa.Float(), nullable=False),
    sa.Column('depth_scale', sa.Float(), nullable=False),
    sa.Column('motor_positions', sa.Text(), nullable=False),
    sa.Column('arm_motor_ids', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_row_id'], ['scan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index('idx_scans_session', ['session_row_id', 'scan_id'], unique=False)

    op.create_table('calibration_capture_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('blob_key', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capture_id'], ['calibration_captures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('capture_id', 'kind')
    )
    with op.batch_alter_table('calibration_capture_artifacts', schema=None) as batch_op:
        batch_op.create_index('idx_calibration_capture_artifacts_capture', ['capture_id'], unique=False)

    op.create_table('waypoints',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('joint_values', sa.Text(), nullable=False),
    sa.Column('joint_names', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'name')
    )
    with op.batch_alter_table('waypoints', schema=None) as batch_op:
        batch_op.create_index('idx_waypoints_robot', ['robot_id', 'name'], unique=False)

    op.create_table('waypoint_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('robot_id', 'name')
    )
    with op.batch_alter_table('waypoint_groups', schema=None) as batch_op:
        batch_op.create_index('idx_waypoint_groups_robot', ['robot_id', 'name'], unique=False)

    op.create_table('waypoint_group_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('waypoint_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['waypoint_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['waypoint_id'], ['waypoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'waypoint_id')
    )
    with op.batch_alter_table('waypoint_group_members', schema=None) as batch_op:
        batch_op.create_index('idx_wgm_group', ['group_id', 'position'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waypoint_group_members', schema=None) as batch_op:
        batch_op.drop_index('idx_wgm_group')

    op.drop_table('waypoint_group_members')
    with op.batch_alter_table('waypoint_groups', schema=None) as batch_op:
        batch_op.drop_index('idx_waypoint_groups_robot')

    op.drop_table('waypoint_groups')
    with op.batch_alter_table('waypoints', schema=None) as batch_op:
        batch_op.drop_index('idx_waypoints_robot')

    op.drop_table('waypoints')
    with op.batch_alter_table('calibration_capture_artifacts', schema=None) as batch_op:
        batch_op.drop_index('idx_calibration_capture_artifacts_capture')

    op.drop_table('calibration_capture_artifacts')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index('idx_scans_session')

    op.drop_table('scans')
    with op.batch_alter_table('reconstructions', schema=None) as batch_op:
        batch_op.drop_index('idx_reconstructions_session')

    op.drop_table('reconstructions')
    with op.batch_alter_table('calibration_results', schema=None) as batch_op:
        batch_op.drop_index('idx_calibration_results_lookup')
        batch_op.drop_index('idx_calibration_results_active', sqlite_where=sa.text('is_active = 1'), postgresql_where=sa.text('is_active = TRUE'))

    op.drop_table('calibration_results')
    with op.batch_alter_table('calibration_captures', schema=None) as batch_op:
        batch_op.drop_index('idx_calibration_captures_run')

    op.drop_table('calibration_captures')
    with op.batch_alter_table('scan_sessions', schema=None) as batch_op:
        batch_op.drop_index('idx_scan_sessions_robot')

    op.drop_table('scan_sessions')
    with op.batch_alter_table('calibration_runs', schema=None) as batch_op:
        batch_op.drop_index('idx_calibration_runs_in_progress', sqlite_where=sa.text("status = 'in_progress'"), postgresql_where=sa.text("status = 'in_progress'"))

    op.drop_table('calibration_runs')
    # ### end Alembic commands ###
