"""MotorBackend Protocol — Motor 도메인의 hardware adapter 계약.

backend.md §16.4 (driver Protocol) + §16.5 (driver self-declare)
정합. Module SDK internal — 외부 import 박지 X (TS gen / catalog viewer
read 대상 X, §8.2).
"""

from __future__ import annotations

from typing import Protocol

from ..contract import MotorCapabilities, MotorTopology


class MotorBackend(Protocol):
    """Hardware adapter — Dynamixel / Feetech / mock 의 공통 계약."""

    # ── self-declare ──
    def capabilities(self) -> MotorCapabilities: ...
    def topology(self) -> MotorTopology: ...

    # ── lifecycle ──
    def open(self) -> None: ...
    def close(self) -> None: ...

    # ── read (state stream 20Hz) ──
    def read_positions(self) -> list[int]: ...
    def read_velocities(self) -> list[int] | None: ...
    def read_loads(self) -> list[int] | None: ...

    # ── driver control state (Motor.Stream.STATE, 저빈도) ──
    def get_torque_enabled(self) -> bool: ...

    # ── write (control service / 100Hz command stream from Motion) ──
    def set_torque(self, enabled: bool) -> None: ...
    def reboot(self) -> None: ...
    def set_gripper(self, position_raw: int) -> None: ...
    def write_positions(self, positions_raw: list[int]) -> None: ...
